### ISSUE TITLE
null reference exception while initializing with TShock master-development

### ISSUE THREAD

**Issue by TheBambino** [Quinci135/SEconomy#2]
Will not load upon starting the server. The master-development branch of TShock is causing SEconomy to throw a null reference exception then plugin initialization aborts.  

As of posting this, the TShock master-development is at commit 0d214d8663fd716c85e2ead4c665f50ec3f2b501
https://github.com/Pryaxis/TShock/commit/0d214d8663fd716c85e2ead4c665f50ec3f2b501
 
I wouldn't be so quick to switch over if it were not for the experimental version addressing the very important and common issue of players being able to dupe coins.

```
[Server API] Error Startup aborted due to an exception in the Server API initialization:
System.InvalidOperationException: Plugin "SEconomy (Milestone 1) Update 23" has thrown an exception during initialization. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Wolfje.Plugins.SEconomy.SEconomyPlugin.Initialize()
   at TerrariaApi.Server.ServerApi.LoadPlugins() in C:\TShock\TerrariaServerAPI\TerrariaServerAPI\TerrariaApi.Server\ServerApi.cs:line 349
   --- End of inner exception stack trace ---
   at TerrariaApi.Server.ServerApi.LoadPlugins() in C:\TShock\TerrariaServerAPI\TerrariaServerAPI\TerrariaApi.Server\ServerApi.cs:line 354
   at TerrariaApi.Server.ServerApi.Initialize(String[] commandLineArgs, Main game) in C:\TShock\TerrariaServerAPI\TerrariaServerAPI\TerrariaApi.Server\ServerApi.cs:line 117
   at TerrariaApi.Server.HookManager.InitialiseAPI() in C:\TShock\TerrariaServerAPI\TerrariaServerAPI\TerrariaApi.Server\HookManager.cs:line 27
```

**Comment by Quinci135** [comment]
Config reference is fixed with d255cec2d40358cd14bae688b5d3fecd457d8704
